/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  NotificationOptions,
} from './interfaces';
import {
  AnimationIn,
  AnimationOut,
  NotificationType,
} from './types';


export namespace Components {

  interface NotificationController {
    'animationIn': AnimationIn;
    'animationOut': AnimationOut;
    'error': (opts: string | NotificationOptions) => void;
    'success': (opts: string | NotificationOptions) => void;
  }
  interface NotificationControllerAttributes extends StencilHTMLAttributes {
    'animationIn'?: AnimationIn;
    'animationOut'?: AnimationOut;
  }

  interface AppNotification {
    'animationIn': AnimationIn;
    'animationOut': AnimationOut;
    'dismissOnClick': boolean;
    'duration': number;
    'errorIcon': string;
    'message': string;
    'successIcon': string;
    'type': NotificationType;
  }
  interface AppNotificationAttributes extends StencilHTMLAttributes {
    'animationIn'?: AnimationIn;
    'animationOut'?: AnimationOut;
    'dismissOnClick'?: boolean;
    'duration'?: number;
    'errorIcon'?: string;
    'message'?: string;
    'onNotificationCompleted'?: (event: CustomEvent) => void;
    'successIcon'?: string;
    'type'?: NotificationType;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NotificationController': Components.NotificationController;
    'AppNotification': Components.AppNotification;
  }

  interface StencilIntrinsicElements {
    'notification-controller': Components.NotificationControllerAttributes;
    'app-notification': Components.AppNotificationAttributes;
  }


  interface HTMLNotificationControllerElement extends Components.NotificationController, HTMLStencilElement {}
  var HTMLNotificationControllerElement: {
    prototype: HTMLNotificationControllerElement;
    new (): HTMLNotificationControllerElement;
  };

  interface HTMLAppNotificationElement extends Components.AppNotification, HTMLStencilElement {}
  var HTMLAppNotificationElement: {
    prototype: HTMLAppNotificationElement;
    new (): HTMLAppNotificationElement;
  };

  interface HTMLElementTagNameMap {
    'notification-controller': HTMLNotificationControllerElement
    'app-notification': HTMLAppNotificationElement
  }

  interface ElementTagNameMap {
    'notification-controller': HTMLNotificationControllerElement;
    'app-notification': HTMLAppNotificationElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
